[server]
listen_addr = "127.0.0.1:8082"

[gossip]
bind_addr = "127.0.0.1:7948"
gossip_interval_ms = 1000
ping_timeout_ms = 500
suspect_timeout_ms = 5000
seed_nodes = ["127.0.0.1:7946"]

[health_check]
check_interval_seconds = 5
check_timeout_seconds = 2

[[backends]]
addr = "127.0.0.1:3000"
weight = 1

[[backends]]
addr = "127.0.0.1:3001"
weight = 1