[server]
listen_addr = "127.0.0.1:8080"

[gossip]
bind_addr = "127.0.0.1:7946"

[[backends]]
addr = "127.0.0.1:3000"
weight = 1

[[backends]]
addr = "127.0.0.1:3001"
weight = 1 

[health_check]
check_interval_seconds = 5
check_timeout_seconds = 2
